import 'package:glue/module.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/button_style.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/color_scheme_dark.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/color_scheme_light.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/colors.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/drag_start_behavior.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/dynamic_scheme_variant.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/floating_action_button_location.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/text_theme.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/theme.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/theme_dark.dart';
import 'package:glue_flutter/src/lib/ui/material/styles/theme_light.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/action_chip.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/alert_dialog.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/app_bar.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/back_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/badge.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/bottom_app_bar.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/bottom_sheet.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/card.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/checkbox.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/chip.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/choice_chip.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/circular_progress_indicator.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/close_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/data_table.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/date_picker_dialog.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/divider.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/drawer.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/drawer_header.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/dropdown_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/elevated_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/expansion_panel_list.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/expansion_tile.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/filled_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/filled_tonal_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/filter_chip.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/floating_action_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/icon_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/ink_well.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/input_chip.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/linear_progress_indicator.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/list_tile.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/material.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/menu_anchor.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/navigation-destination.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/navigation_bar.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/navigation_drawer.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/navigation_rail.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/outlined_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/popup_menu_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/radio.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/refresh_indicator.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/scaffold.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/search_anchor.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/search_bar.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/segmented_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/show_bottom_sheet.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/show_dialog.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/show_modal_bottom_sheet.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/slider.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/snack_bar.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/stepper.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/switch.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/tab_bar.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/tab_bar_view.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/text_button.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/text_field.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/time_picker_dialog.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/tooltip.dart';
import 'package:glue_flutter/src/lib/ui/material/widgets/user_accounts_drawer_header.dart';

final ModuleInfo uiMaterialModule = nativeModule('ffi.ui.material', [
  // Material widgets
  ('app-bar', appBar),
  ('scaffold', scaffold),
  ('back-button', backButton),
  ('button', button),
  ('close-button', closeButton),
  ('filled-button', filledButton),
  ('filled-tonal-button', filledTonalButton),
  ('outlined-button', outlinedButton),
  ('elevated-button', elevatedButton),
  ('icon-button', iconButton),
  ('segmented-button', segmentedButton),
  ('text-button', textButton),
  ('ink-well', inkWell),
  ('card', card),
  ('filled-card', filledCard),
  ('outlined-card', outlinedCard),
  ('list-tile', listTile),
  ('snack-bar', snackBar),
  ('text-field', textField),
  ('floating-action-button', floatingActionButton),
  ('checkbox', checkbox),
  ('switch', switchWidget),
  ('linear-progress-indicator', linearProgressIndicator),
  ('badge', badge),
  ('divider', divider),
  ('radio', radio),
  ('slider', slider),
  ('alert-dialog', alertDialog),
  ('chip', chip),
  ('drawer', drawer),
  ('date-picker-dialog', datePickerDialog),
  ('time-picker-dialog', timePickerDialog),
  ('tab-bar', tabBar),
  ('menu-anchor', menuAnchor),
  ('expansion-tile', expansionTile),
  ('data-table', dataTable),
  ('tooltip', tooltip),
  ('popup-menu-button', popupMenuButton),
  ('dropdown-button', dropdownButton),
  ('refresh-indicator', refreshIndicator),
  ('circular-progress-indicator', circularProgressIndicator),
  ('stepper', stepper),
  ('expansion-panel-list', expansionPanelList),
  ('tab-bar-view', tabBarView),
  ('bottom-sheet', bottomSheet),
  ('search-bar', searchBar),
  ('search-anchor', searchAnchor),
  ('input-chip', inputChip),
  ('filter-chip', filterChip),
  ('choice-chip', choiceChip),
  ('action-chip', actionChip),
  ('bottom-app-bar', bottomAppBar),
  ('navigation-bar', navigationBar),
  ('navigation-destination', navigationDestination),
  ('navigation-drawer', navigationDrawer),
  ('navigation-rail', navigationRail),
  ('drawer-header', drawerHeader),
  ('user-accounts-drawer-header', userAccountsDrawerHeader),
  ('material', material),

  // Material enum union objects
  ('colors', colors),
  ('drag-start-behavior', dragStartBehavior),
  ('floating-action-button-location', floatingActionButtonLocation),
  ('dynamic-scheme-variant', dynamicSchemeVariant),
  // Material theme functions and objects
  ('theme-dark', themeDark),
  ('theme-light', themeLight),
  ('theme', theme),
  ('color-scheme-light', colorSchemeLight),
  ('color-scheme-dark', colorSchemeDark),
  ('text-theme', textTheme),

  ('button-style', buttonStyle),

  ('show-dialog', showDialog_),
  ('show-bottom-sheet', showBottomSheet_),
  ('show-modal-bottom-sheet', showModalBottomSheet_),
]);
