### Successful begin to register
POST http://localhost:3000/register/begin HTTP/1.1
content-type: application/json

{
    "name" : "john",
    "displayName" : "John Doe"
}

### Invalid begin to register
POST http://localhost:3000/register/begin HTTP/1.1
content-type: application/json

{
    "name": " ",
    "displayName": " "
}

### Invalid begin to register
POST http://localhost:3000/register/begin HTTP/1.1
content-type: application/json

{}

### Invalid begin to register
POST http://localhost:3000/register/begin HTTP/1.1
