### Successful start to register
POST http://localhost:3000/register/start HTTP/1.1
content-type: application/json

{
    "name" : "john",
    "displayName" : "John Doe"
}

### Invalid start to register
POST http://localhost:3000/register/start HTTP/1.1
content-type: application/json

{
    "name": "",
    "displayName": ""
}

### Invalid start to register
POST http://localhost:3000/register/start HTTP/1.1
content-type: application/json

{}
