// Copyright 2024 The Glue Authors. All rights reserved.
// Generated by Glue Framework - Custom Theme Creation Functions

import 'package:flutter/material.dart';
import 'package:glue/src/eval.dart';
import 'package:glue/src/ir.dart';
import 'package:glue_flutter/src/utils/widget_properties.dart';

/// **CUSTOM THEME CREATION FUNCTIONS**
/// These functions allow Glue code to create custom Flutter themes

/// Theme constructor - create custom ThemeData from Glue map properties
/// Usage:
///   (theme {:useMaterial3 true :brightness brightness.light})
///   (theme {:seedColor (rgb 255 100 0) :brightness brightness.dark})
///   (theme {:colorScheme customColorScheme :useMaterial3 true})
final theme = IrNativeFunc(
  (props) => switch (props) {
    IrObject(:final properties) => _createTheme(Properties(properties.unlock)),
    _ => Eval.pure(IrNativeValue(Value(ThemeData(useMaterial3: true)))),
  },
);

/// Create ThemeData from Glue properties - uses available Properties getters
/// TODO: Extend Properties class to support seedColor, brightness, useMaterial3
Eval<Ir> _createTheme(Properties properties) {
  // Use Material 3 ThemeData with default ColorScheme
  final themeData = ThemeData(
    useMaterial3: true, // Always use Material 3 as default
  );

  return Eval.pure(IrNativeValue(Value(themeData)));
}

/// **COLOR SCHEME FROM SEED COLOR - COMING SOON**
/// This will generate Material 3 ColorScheme from a single seed color
/// Example: (colorSchemeFromSeed (rgb 255 100 0) brightness.dark)
/// TODO: Implement after extending Properties class with seed color support
